spring:
  # 数据库配置
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/health_system?useUnicode=true&characterEncoding=UTF-8&serverTimezone=UTC
    username: root
    password: 123456
    hikari:
      maximum-pool-size: 10   # 连接池最大连接数
      minimum-idle: 5          # 最小空闲连接数
      idle-timeout: 30000      # 空闲连接最大保留时间
      connection-timeout: 30000  # 连接超时时间
      pool-name: HikariCP       # 连接池名称

  # redis配置
  data:
    redis:
      host: localhost
      port: 6379
      password: ""

  # 文件上传设置
  servlet:
    multipart:
      enabled: true
      max-file-size: 500MB
      max-request-size: 1GB

  # 日期格式化
  jackson:
    date-format: yyyy-MM-dd HH:mm:ss
    time-zone: GMT+8

mybatis-plus:
  type-aliases-package: org.example.domain.pojo
  global-config:
    db-config:
      id-type: auto
      logic-delete-field: deleted  # 全局逻辑删除的实体字段名
      logic-delete-value: 1        # 逻辑已删除值(默认为1)
      logic-not-delete-value: 0    # 逻辑未删除值(默认为0)
  configuration:
    default-enum-type-handler: com.baomidou.mybatisplus.core.handlers.MybatisEnumTypeHandler
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
    map-underscore-to-camel-case: true
  type-handlers-package: org.example.Handler

server:
  port: 8080  # 设置服务器端口

logging:
  file:
    name: src/main/resources/myApp.log

knife4j:
  enable: true
  setting:
    language: zh_cn
  basic:
    enable: true
    username: admin
    password: admin

# 科大讯飞API配置
xfyun:
  appId: 90f693db
  secretKey: 5807bc828335e6cc9c2858b2a285454c

